TrajectoryPlannerROS:
  max_vel_x: 0.705
  min_vel_x: 0.25
  max_vel_theta: 3.351
  min_vel_theta: -3.0
  min_in_place_vel_theta: 0.92

  acc_lim_theta: 3.0
  escape_vel: -0.4

  xy_goal_tolerance: 0.5
  yaw_goal_tolerance: 0.5
  holonomic_robot: false
