obstacle_range: 2.0
raytrace_range: 2.0
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.14
inflation_radius: 0.20

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}
