obstacle_range: 2.0
raytrace_range: 2.0
footprint: [[-0.088, 0.1875], [0.088, 0.1875], [0.088, -0.1875], [-0.088, -0.1875]]
#robot_radius: 0.14
inflation_radius: 0.20

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}
